spring:
  datasource:
    dbcp2:
      initial-size: 10
      max-total: 100
    driver-class-name: org.postgresql.Driver
    password: root
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:postgresql:ntsp712db
    username: postgres
